spring:
    banner:
        location: classpath:/banner.txt
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      defer-datasource-initialization: true
    h2:
      console:
        enabled: true
    sql:
      init:
        mode: always
        data-locations: classpath:/data.sql
        
        
server:
    port: 8080
